### ISSUE TITLE
Feature Request: Adjust focal area for non-eye tracked headsets (FFR)

### ISSUE THREAD

**Issue by sleighzy** [TallyMouse/QuadViewsCompanion#1]
There has been a large uptake in the amount of DCS users using Quad Views now that it is more discoverable.

The majority of headset users however do not have eye tracking so are unable to use this tool to adjust the focal area and need to manually add/edit the `C:\Users\username\AppData\Local\Quad-Views-Foveated\settings.cfg` file themselves to add the `horizontal_fixed_section` and `vertical_fixed_section` values. This is not immediately obvious in the tool so some users think they are updating this when in actual fact they aren't. It would be a huge win if this companion app could also apply that setting to those values for FFR and not just the `horizontal_focus_section` and `vertical_focus_section` values for DFR.

Current default configuration for this:

```
# Fixed Foveated rendering settings for fallback when eye tracker is not available.
horizontal_fixed_section=0.5
vertical_fixed_section=0.45
```

This change would mean that many more users would be able to use this fantastic tool. I'd share this wide and far if implemented.

Thanks in advance.

**Comment by TallyMouse** [comment]
Hi!   Thanks for the suggestion.   

I've updated QVC to V1.0.14 accordingly.

**Comment by sleighzy** [comment]
Thank you so much. Good to see it applies to all headsets, I'll let the folk know.
